
###
GET http://localhost:8088/todos

###

POST http://localhost:8088/todos
Content-Type: application/json

{
    "title": "Learn diesel.rs" 
}

###
PUT http://localhost:8088/todos/0dfa32da-a07f-4961-a8cd-09742061d5de
Content-Type: application/json

{
    "title": "Updated sisas",
    "completed": true
}

###
PATCH http://localhost:8088/todos/716e6003-72dc-4790-9d9e-496c90f26295
Content-Type: application/json

{
    "completed": true
}

### 
DELETE http://localhost:8088/todos/0dfa32da-a07f-4961-a8cd-09742061d5de

### Register User

POST http://localhost:8088/register
Content-Type: application/json

{
    "email": "d.cardona.rojas@gmail.com",
    "password": "123423345"
}

### Login User

POST http://localhost:8088/auth
Content-Type: application/json

{
    "email": "d.cardona.rojas@gmail.com",
    "password": "123423345"
}